### ISSUE TITLE
golang ssh library cannot connect to sf.tmate.io

### ISSUE THREAD

**Issue by drnic** [tmate-io/tmate-slave#12]
I was trying to use go.crypto to connect to the sf.tmate.io SSH session but get the following error:

```
unable to connect: ssh: handshake failed: ssh: no common algorithms
```

I found an explanation for the possible cause: http://stackoverflow.com/questions/18998473/failed-to-dial-handshake-failed-ssh-no-common-algorithms-error-in-ssh-client/19002265#19002265

Currently, I've fallen back to calling out to an external `ssh` CLI [1] but unfortunately for the Windows users it means they need to find and install an SSH client CLI.

It would be awesome if sf.tmate.io supported one of the cyphers supported by go-crypto which I think are:

* aes128-ctr
* aes192-ctr
* aes256-ctr
* arcfour128
* arcfour256

Possible?

[1] https://github.com/cloudfoundry-community/cf-ssh#why-require-ssh-cli

**Comment by allomov** [comment]
@drnic hope that this merging this PR to golang will help in this problem https://github.com/golang/go/issues/10274 soon.
