### ISSUE TITLE
unable to ./configure - no MSGPACK

### ISSUE THREAD

**Issue by ytti** [tmate-io/tmate-slave#16]
configure: error: "msgpack >= 1.2.0 not found"

All these are installed:
root@tmate:~/tmate-slave# apt-cache search libmsgpack
libmsgpack-dev - binary-based efficient object serialization library
libmsgpack3 - binary-based efficient object serialization library
libmsgpackc2 - binary-based efficient object serialization library
root@tmate:~/tmate-slave#

Same machine was able able to compile tmate-slave 2-3 months ago.

**Comment by nviennot** [comment]
yeah, 2-3 months ago, tmate-slave didn't required an up to date version of msgpack, but now it does.

Try installing a more recent version of msgpack

**Comment by ytti** [comment]
Crap, debian/unstable does not ship with newer. Gotta build that first. Thanks.
