### ISSUE TITLE
Limit access to tmate-slave

### ISSUE THREAD

**Issue by varac** [tmate-io/tmate-slave#37]
I'd like to run my own tmate-slave server, but if I understand correctly, everybody could connectand start new sessions. Is there a way to limit access to it, i.e. based on the ssh pubkey that is connecting ?
This way, I could invite friends but not thw whole world.

**Comment by nviennot** [comment]
Yes, but you have to implement the logic.
At this location: https://github.com/tmate-io/tmate-slave/blob/master/tmate-ssh-server.c#L121 `SSH_AUTH_SUCCESS` is always returned. You can return `SSH_AUTH_DENIED` based on the value of `pubkey`.

**Comment by varac** [comment]
Good to know. A user-friendly implementation without poking around in C code would be great (Where do I specify the authorized_keys etc).

**Comment by slashmili** [comment]
If I understand it correctly, this repo allow to have a server to check the public keys. But is there any possibility to check user A's local machine ~/.ssh/authorized_keys file?

**Comment by nviennot** [comment]
@slashmili not at the moment

**Comment by varac** [comment]
Closing this issue since https://github.com/tmate-io/tmate-slave/pull/38 got merged. Thanks @juniorz !!
